version: '2'

services:

  nginx:
    image: nginx:latest
    volumes:
      - "./files:/files"
      - "./conf:/etc/nginx/conf.d"
    ports:
      - "80:80"
    networks:
      - files

networks:

  files:
    driver: bridge
